app:
    resource: "@AppBundle/Controller/"
    type:     annotation

admin:
    resource: "@AppBundle/Controller/Admin"
    type:     annotation
    prefix :  /admin

logout:
    path: /logout